# Определяем имя workflow
name: Run Linters and Tests

# Указываем триггеры для запуска workflow
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  merge_group:
    types: [ checks_requested ]
  pull_request:
    types: [ ready_for_review ]

# Определяем jobs, которые будут выполняться в рамках workflow
jobs:
  go-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Run go vet
        working-directory: clean
        run: go vet ./...

      - name: Run go test
        working-directory: clean
        run: go test -v --short ./...

  golangci:
    runs-on: ubuntu-latest
    needs: go-tools
    steps:
      - uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          working-directory: clean
          args: --timeout 10m
